//
//  PVAttrIdentifiers.h
//  PickView
//
//  Created by kris cheng on 2026/7/9.
//

#import <Foundation/Foundation.h>

#pragma mark - Group

typedef NSString * PVAttrGroupIdentifier;

extern PVAttrGroupIdentifier const PVAttrGroup_None;
extern PVAttrGroupIdentifier const PVAttrGroup_Class;
extern PVAttrGroupIdentifier const PVAttrGroup_Relation;
extern PVAttrGroupIdentifier const PVAttrGroup_Layout;
extern PVAttrGroupIdentifier const PVAttrGroup_AutoLayout;
extern PVAttrGroupIdentifier const PVAttrGroup_ViewLayer;

extern PVAttrGroupIdentifier const PVAttrGroup_UIImageView;
extern PVAttrGroupIdentifier const PVAttrGroup_UILabel;
extern PVAttrGroupIdentifier const PVAttrGroup_UIControl;
extern PVAttrGroupIdentifier const PVAttrGroup_UIButton;
extern PVAttrGroupIdentifier const PVAttrGroup_UIScrollView;
extern PVAttrGroupIdentifier const PVAttrGroup_UITableView;
extern PVAttrGroupIdentifier const PVAttrGroup_UITextView;
extern PVAttrGroupIdentifier const PVAttrGroup_UITextField;
extern PVAttrGroupIdentifier const PVAttrGroup_UIVisualEffectView;
extern PVAttrGroupIdentifier const PVAttrGroup_UIStackView;

extern PVAttrGroupIdentifier const PVAttrGroup_NSImageView;
extern PVAttrGroupIdentifier const PVAttrGroup_NSControl;
extern PVAttrGroupIdentifier const PVAttrGroup_NSButton;
extern PVAttrGroupIdentifier const PVAttrGroup_NSScrollView;
extern PVAttrGroupIdentifier const PVAttrGroup_NSTableView;
extern PVAttrGroupIdentifier const PVAttrGroup_NSTextView;
extern PVAttrGroupIdentifier const PVAttrGroup_NSTextField;
extern PVAttrGroupIdentifier const PVAttrGroup_NSVisualEffectView;
extern PVAttrGroupIdentifier const PVAttrGroup_NSStackView;
extern PVAttrGroupIdentifier const PVAttrGroup_NSWindow;

// UITraitCollection
extern PVAttrGroupIdentifier const PVAttrGroup_UITraitCollection;

extern PVAttrGroupIdentifier const PVAttrGroup_UserCustom;

#pragma mark - Section

typedef NSString * PVAttrSectionIdentifier;

extern PVAttrSectionIdentifier const PVAttrSec_None;

extern PVAttrSectionIdentifier const PVAttrSec_UserCustom;

extern PVAttrSectionIdentifier const PVAttrSec_Class_Class;

extern PVAttrSectionIdentifier const PVAttrSec_Relation_Relation;

extern PVAttrSectionIdentifier const PVAttrSec_Layout_Frame;
extern PVAttrSectionIdentifier const PVAttrSec_Layout_Bounds;
extern PVAttrSectionIdentifier const PVAttrSec_Layout_SafeArea;
extern PVAttrSectionIdentifier const PVAttrSec_Layout_Position;
extern PVAttrSectionIdentifier const PVAttrSec_Layout_AnchorPoint;

extern PVAttrSectionIdentifier const PVAttrSec_AutoLayout_Hugging;
extern PVAttrSectionIdentifier const PVAttrSec_AutoLayout_Resistance;
extern PVAttrSectionIdentifier const PVAttrSec_AutoLayout_Constraints;
extern PVAttrSectionIdentifier const PVAttrSec_AutoLayout_IntrinsicSize;

extern PVAttrSectionIdentifier const PVAttrSec_ViewLayer_Visibility;
extern PVAttrSectionIdentifier const PVAttrSec_ViewLayer_InterationAndMasks;
extern PVAttrSectionIdentifier const PVAttrSec_ViewLayer_Corner;
extern PVAttrSectionIdentifier const PVAttrSec_ViewLayer_BgColor;
extern PVAttrSectionIdentifier const PVAttrSec_ViewLayer_Border;
extern PVAttrSectionIdentifier const PVAttrSec_ViewLayer_Shadow;
extern PVAttrSectionIdentifier const PVAttrSec_ViewLayer_Tag;

extern PVAttrSectionIdentifier const PVAttrSec_ViewLayer_ContentMode;
extern PVAttrSectionIdentifier const PVAttrSec_ViewLayer_TintColor;

extern PVAttrSectionIdentifier const PVAttrSec_UIImageView_Name;
extern PVAttrSectionIdentifier const PVAttrSec_UIImageView_Open;

extern PVAttrSectionIdentifier const PVAttrSec_UILabel_Text;
extern PVAttrSectionIdentifier const PVAttrSec_UILabel_Font;
extern PVAttrSectionIdentifier const PVAttrSec_UILabel_NumberOfLines;
extern PVAttrSectionIdentifier const PVAttrSec_UILabel_TextColor;
extern PVAttrSectionIdentifier const PVAttrSec_UILabel_BreakMode;
extern PVAttrSectionIdentifier const PVAttrSec_UILabel_Alignment;
extern PVAttrSectionIdentifier const PVAttrSec_UILabel_CanAdjustFont;

extern PVAttrSectionIdentifier const PVAttrSec_UIControl_EnabledSelected;
extern PVAttrSectionIdentifier const PVAttrSec_UIControl_VerAlignment;
extern PVAttrSectionIdentifier const PVAttrSec_UIControl_HorAlignment;
extern PVAttrSectionIdentifier const PVAttrSec_UIControl_QMUIOutsideEdge;

extern PVAttrSectionIdentifier const PVAttrSec_UIButton_ContentInsets;
extern PVAttrSectionIdentifier const PVAttrSec_UIButton_TitleInsets;
extern PVAttrSectionIdentifier const PVAttrSec_UIButton_ImageInsets;

extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_ContentInset;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_AdjustedInset;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_IndicatorInset;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_Offset;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_ContentSize;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_Behavior;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_ShowsIndicator;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_Bounce;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_ScrollPaging;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_ContentTouches;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_Zoom;
extern PVAttrSectionIdentifier const PVAttrSec_UIScrollView_QMUIInitialInset;

extern PVAttrSectionIdentifier const PVAttrSec_UITableView_Style;
extern PVAttrSectionIdentifier const PVAttrSec_UITableView_SectionsNumber;
extern PVAttrSectionIdentifier const PVAttrSec_UITableView_RowsNumber;
extern PVAttrSectionIdentifier const PVAttrSec_UITableView_SeparatorStyle;
extern PVAttrSectionIdentifier const PVAttrSec_UITableView_SeparatorColor;
extern PVAttrSectionIdentifier const PVAttrSec_UITableView_SeparatorInset;

extern PVAttrSectionIdentifier const PVAttrSec_UITextView_Basic;
extern PVAttrSectionIdentifier const PVAttrSec_UITextView_Text;
extern PVAttrSectionIdentifier const PVAttrSec_UITextView_Font;
extern PVAttrSectionIdentifier const PVAttrSec_UITextView_TextColor;
extern PVAttrSectionIdentifier const PVAttrSec_UITextView_Alignment;
extern PVAttrSectionIdentifier const PVAttrSec_UITextView_ContainerInset;

extern PVAttrSectionIdentifier const PVAttrSec_UITextField_Text;
extern PVAttrSectionIdentifier const PVAttrSec_UITextField_Placeholder;
extern PVAttrSectionIdentifier const PVAttrSec_UITextField_Font;
extern PVAttrSectionIdentifier const PVAttrSec_UITextField_TextColor;
extern PVAttrSectionIdentifier const PVAttrSec_UITextField_Alignment;
extern PVAttrSectionIdentifier const PVAttrSec_UITextField_Clears;
extern PVAttrSectionIdentifier const PVAttrSec_UITextField_CanAdjustFont;
extern PVAttrSectionIdentifier const PVAttrSec_UITextField_ClearButtonMode;

extern PVAttrSectionIdentifier const PVAttrSec_UIVisualEffectView_Style;
extern PVAttrSectionIdentifier const PVAttrSec_UIVisualEffectView_QMUIForegroundColor;

extern PVAttrSectionIdentifier const PVAttrSec_UIStackView_Axis;
extern PVAttrSectionIdentifier const PVAttrSec_UIStackView_Distribution;
extern PVAttrSectionIdentifier const PVAttrSec_UIStackView_Alignment;
extern PVAttrSectionIdentifier const PVAttrSec_UIStackView_Spacing;

extern PVAttrSectionIdentifier const PVAttrSec_NSImageView_Name;
extern PVAttrSectionIdentifier const PVAttrSec_NSImageView_Open;
extern PVAttrSectionIdentifier const PVAttrSec_NSImageView_Scaling;
extern PVAttrSectionIdentifier const PVAttrSec_NSImageView_Behavior;
extern PVAttrSectionIdentifier const PVAttrSec_NSImageView_ContentTintColor;

extern PVAttrSectionIdentifier const PVAttrSec_NSControl_State;
extern PVAttrSectionIdentifier const PVAttrSec_NSControl_ControlSize;
extern PVAttrSectionIdentifier const PVAttrSec_NSControl_Font;
extern PVAttrSectionIdentifier const PVAttrSec_NSControl_Alignment;
extern PVAttrSectionIdentifier const PVAttrSec_NSControl_Misc;
extern PVAttrSectionIdentifier const PVAttrSec_NSControl_Value;
extern PVAttrSectionIdentifier const PVAttrSec_NSControl_StringValue;


extern PVAttrSectionIdentifier const PVAttrSec_NSButton_ButtonType;
extern PVAttrSectionIdentifier const PVAttrSec_NSButton_Title;
extern PVAttrSectionIdentifier const PVAttrSec_NSButton_BezelStyle;
extern PVAttrSectionIdentifier const PVAttrSec_NSButton_Bordered;
extern PVAttrSectionIdentifier const PVAttrSec_NSButton_Transparent;
extern PVAttrSectionIdentifier const PVAttrSec_NSButton_BezelColor;
extern PVAttrSectionIdentifier const PVAttrSec_NSButton_ContentTintColor;
extern PVAttrSectionIdentifier const PVAttrSec_NSButton_Misc;

extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_ContentOffset;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_ContentSize;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_ContentInset;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_BorderType;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_Scroller;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_Ruler;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_LineScroll;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_PageScroll;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_ScrollElasiticity;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_Misc;
extern PVAttrSectionIdentifier const PVAttrSec_NSScrollView_Magnification;

extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_RowHeight;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_AutomaticRowHeights;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_IntercellSpacing;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_Style;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_ColumnAutoresizingStyle;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_GridStyleMask;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_SelectionHighlightStyle;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_GridColor;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_RowSizeStyle;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_NumberOfRows;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_NumberOfColumns;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_UseAlternatingRowBackgroundColors;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_AllowsColumnReordering;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_AllowsColumnResizing;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_AllowsMultipleSelection;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_AllowsEmptySelection;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_AllowsColumnSelection;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_AllowsTypeSelect;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_DraggingDestinationFeedbackStyle;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_Autosave;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_FloatsGroupRows;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_RowActionsVisible;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_UsesStaticContents;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_UserInterfaceLayoutDirection;
extern PVAttrSectionIdentifier const PVAttrSec_NSTableView_VerticalMotionCanBeginDrag;


extern PVAttrSectionIdentifier const PVAttrSec_NSTextView_Font;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextView_Basic;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextView_String;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextView_TextColor;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextView_Alignment;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextView_ContainerInset;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextView_BaseWritingDirection;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextView_Size;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextView_Resizable;

extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_Bordered;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_Bezeled;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_BezelStyle;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_Editable;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_Selectable;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_DrawsBackground;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_PreferredMaxLayoutWidth;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_MaximumNumberOfLines;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_AllowsDefaultTighteningForTruncation;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_LineBreakStrategy;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_Placeholder;
extern PVAttrSectionIdentifier const PVAttrSec_NSTextField_TextColor;

extern PVAttrSectionIdentifier const PVAttrSec_NSVisualEffectView_Material;
extern PVAttrSectionIdentifier const PVAttrSec_NSVisualEffectView_InteriorBackgroundStyle;
extern PVAttrSectionIdentifier const PVAttrSec_NSVisualEffectView_BlendingMode;
extern PVAttrSectionIdentifier const PVAttrSec_NSVisualEffectView_State;
extern PVAttrSectionIdentifier const PVAttrSec_NSVisualEffectView_Emphasized;

extern PVAttrSectionIdentifier const PVAttrSec_NSStackView_Orientation;
extern PVAttrSectionIdentifier const PVAttrSec_NSStackView_EdgeInsets;
extern PVAttrSectionIdentifier const PVAttrSec_NSStackView_DetachesHiddenViews;
extern PVAttrSectionIdentifier const PVAttrSec_NSStackView_Distribution;
extern PVAttrSectionIdentifier const PVAttrSec_NSStackView_Alignment;
extern PVAttrSectionIdentifier const PVAttrSec_NSStackView_Spacing;

extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_Title;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_Subtitle;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_State;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_Style;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_CollectionBehavior;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_Appearance;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_TitleVisibility;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_ToolbarStyle;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_TitlebarSeparatorStyle;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_Behavior;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_AnimationBehavior;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_Level;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_TabbingMode;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_Size;
extern PVAttrSectionIdentifier const PVAttrSec_NSWindow_Info;


#pragma mark - Attr

typedef NSString * PVAttrIdentifier;

extern PVAttrIdentifier const PVAttr_None;

/// 用户自定义的
extern PVAttrIdentifier const PVAttr_UserCustom;

extern PVAttrIdentifier const PVAttr_Class_Class_Class;

extern PVAttrIdentifier const PVAttr_Relation_Relation_Relation;

extern PVAttrIdentifier const PVAttr_Layout_Frame_Frame;
extern PVAttrIdentifier const PVAttr_Layout_Bounds_Bounds;
extern PVAttrIdentifier const PVAttr_Layout_SafeArea_SafeArea;
extern PVAttrIdentifier const PVAttr_Layout_Position_Position;
extern PVAttrIdentifier const PVAttr_Layout_AnchorPoint_AnchorPoint;

extern PVAttrIdentifier const PVAttr_AutoLayout_Hugging_Hor;
extern PVAttrIdentifier const PVAttr_AutoLayout_Hugging_Ver;
extern PVAttrIdentifier const PVAttr_AutoLayout_Resistance_Hor;
extern PVAttrIdentifier const PVAttr_AutoLayout_Resistance_Ver;
extern PVAttrIdentifier const PVAttr_AutoLayout_Constraints_Constraints;
extern PVAttrIdentifier const PVAttr_AutoLayout_IntrinsicSize_Size;

extern PVAttrIdentifier const PVAttr_ViewLayer_Visibility_Hidden;
extern PVAttrIdentifier const PVAttr_ViewLayer_Visibility_Opacity;
extern PVAttrIdentifier const PVAttr_ViewLayer_InterationAndMasks_Interaction;
extern PVAttrIdentifier const PVAttr_ViewLayer_InterationAndMasks_MasksToBounds;
extern PVAttrIdentifier const PVAttr_ViewLayer_Corner_Radius;
extern PVAttrIdentifier const PVAttr_ViewLayer_BgColor_BgColor;
extern PVAttrIdentifier const PVAttr_ViewLayer_Border_Color;
extern PVAttrIdentifier const PVAttr_ViewLayer_Border_Width;
extern PVAttrIdentifier const PVAttr_ViewLayer_Shadow_Color;
extern PVAttrIdentifier const PVAttr_ViewLayer_Shadow_Opacity;
extern PVAttrIdentifier const PVAttr_ViewLayer_Shadow_Radius;
extern PVAttrIdentifier const PVAttr_ViewLayer_Shadow_OffsetW;
extern PVAttrIdentifier const PVAttr_ViewLayer_Shadow_OffsetH;
extern PVAttrIdentifier const PVAttr_ViewLayer_ContentMode_Mode;
extern PVAttrIdentifier const PVAttr_ViewLayer_TintColor_Color;
extern PVAttrIdentifier const PVAttr_ViewLayer_TintColor_Mode;
extern PVAttrIdentifier const PVAttr_ViewLayer_Tag_Tag;

extern PVAttrIdentifier const PVAttr_UIImageView_Name_Name;
extern PVAttrIdentifier const PVAttr_UIImageView_Open_Open;

extern PVAttrIdentifier const PVAttr_UILabel_Text_Text;
extern PVAttrIdentifier const PVAttr_UILabel_Font_Name;
extern PVAttrIdentifier const PVAttr_UILabel_Font_Size;
extern PVAttrIdentifier const PVAttr_UILabel_NumberOfLines_NumberOfLines;
extern PVAttrIdentifier const PVAttr_UILabel_TextColor_Color;
extern PVAttrIdentifier const PVAttr_UILabel_Alignment_Alignment;
extern PVAttrIdentifier const PVAttr_UILabel_BreakMode_Mode;
extern PVAttrIdentifier const PVAttr_UILabel_CanAdjustFont_CanAdjustFont;

extern PVAttrIdentifier const PVAttr_UIControl_EnabledSelected_Enabled;
extern PVAttrIdentifier const PVAttr_UIControl_EnabledSelected_Selected;
extern PVAttrIdentifier const PVAttr_UIControl_VerAlignment_Alignment;
extern PVAttrIdentifier const PVAttr_UIControl_HorAlignment_Alignment;
extern PVAttrIdentifier const PVAttr_UIControl_QMUIOutsideEdge_Edge;

extern PVAttrIdentifier const PVAttr_UIButton_ContentInsets_Insets;
extern PVAttrIdentifier const PVAttr_UIButton_TitleInsets_Insets;
extern PVAttrIdentifier const PVAttr_UIButton_ImageInsets_Insets;

extern PVAttrIdentifier const PVAttr_UIScrollView_Offset_Offset;
extern PVAttrIdentifier const PVAttr_UIScrollView_ContentSize_Size;
extern PVAttrIdentifier const PVAttr_UIScrollView_ContentInset_Inset;
extern PVAttrIdentifier const PVAttr_UIScrollView_AdjustedInset_Inset;
extern PVAttrIdentifier const PVAttr_UIScrollView_Behavior_Behavior;
extern PVAttrIdentifier const PVAttr_UIScrollView_IndicatorInset_Inset;
extern PVAttrIdentifier const PVAttr_UIScrollView_ScrollPaging_ScrollEnabled;
extern PVAttrIdentifier const PVAttr_UIScrollView_ScrollPaging_PagingEnabled;
extern PVAttrIdentifier const PVAttr_UIScrollView_Bounce_Ver;
extern PVAttrIdentifier const PVAttr_UIScrollView_Bounce_Hor;
extern PVAttrIdentifier const PVAttr_UIScrollView_ShowsIndicator_Hor;
extern PVAttrIdentifier const PVAttr_UIScrollView_ShowsIndicator_Ver;
extern PVAttrIdentifier const PVAttr_UIScrollView_ContentTouches_Delay;
extern PVAttrIdentifier const PVAttr_UIScrollView_ContentTouches_CanCancel;
extern PVAttrIdentifier const PVAttr_UIScrollView_Zoom_MinScale;
extern PVAttrIdentifier const PVAttr_UIScrollView_Zoom_MaxScale;
extern PVAttrIdentifier const PVAttr_UIScrollView_Zoom_Scale;
extern PVAttrIdentifier const PVAttr_UIScrollView_Zoom_Bounce;
extern PVAttrIdentifier const PVAttr_UIScrollView_QMUIInitialInset_Inset;

extern PVAttrIdentifier const PVAttr_UITableView_Style_Style;
extern PVAttrIdentifier const PVAttr_UITableView_SectionsNumber_Number;
extern PVAttrIdentifier const PVAttr_UITableView_RowsNumber_Number;
extern PVAttrIdentifier const PVAttr_UITableView_SeparatorInset_Inset;
extern PVAttrIdentifier const PVAttr_UITableView_SeparatorColor_Color;
extern PVAttrIdentifier const PVAttr_UITableView_SeparatorStyle_Style;

extern PVAttrIdentifier const PVAttr_UITextView_Font_Name;
extern PVAttrIdentifier const PVAttr_UITextView_Font_Size;
extern PVAttrIdentifier const PVAttr_UITextView_Basic_Editable;
extern PVAttrIdentifier const PVAttr_UITextView_Basic_Selectable;
extern PVAttrIdentifier const PVAttr_UITextView_Text_Text;
extern PVAttrIdentifier const PVAttr_UITextView_TextColor_Color;
extern PVAttrIdentifier const PVAttr_UITextView_Alignment_Alignment;
extern PVAttrIdentifier const PVAttr_UITextView_ContainerInset_Inset;

extern PVAttrIdentifier const PVAttr_UITextField_Text_Text;
extern PVAttrIdentifier const PVAttr_UITextField_Placeholder_Placeholder;
extern PVAttrIdentifier const PVAttr_UITextField_Font_Name;
extern PVAttrIdentifier const PVAttr_UITextField_Font_Size;
extern PVAttrIdentifier const PVAttr_UITextField_TextColor_Color;
extern PVAttrIdentifier const PVAttr_UITextField_Alignment_Alignment;
extern PVAttrIdentifier const PVAttr_UITextField_Clears_ClearsOnBeginEditing;
extern PVAttrIdentifier const PVAttr_UITextField_Clears_ClearsOnInsertion;
extern PVAttrIdentifier const PVAttr_UITextField_CanAdjustFont_CanAdjustFont;
extern PVAttrIdentifier const PVAttr_UITextField_CanAdjustFont_MinSize;
extern PVAttrIdentifier const PVAttr_UITextField_ClearButtonMode_Mode;

extern PVAttrIdentifier const PVAttr_UIVisualEffectView_Style_Style;
extern PVAttrIdentifier const PVAttr_UIVisualEffectView_QMUIForegroundColor_Color;

extern PVAttrIdentifier const PVAttr_UIStackView_Axis_Axis;
extern PVAttrIdentifier const PVAttr_UIStackView_Distribution_Distribution;
extern PVAttrIdentifier const PVAttr_UIStackView_Alignment_Alignment;
extern PVAttrIdentifier const PVAttr_UIStackView_Spacing_Spacing;

extern PVAttrIdentifier const PVAttr_NSImageView_Name_Name;
extern PVAttrIdentifier const PVAttr_NSImageView_Open_Open;
extern PVAttrIdentifier const PVAttr_NSImageView_Scaling_ImageScaling;
extern PVAttrIdentifier const PVAttr_NSImageView_Scaling_ImageAlignment;
extern PVAttrIdentifier const PVAttr_NSImageView_Scaling_ImageFrameStyle;
extern PVAttrIdentifier const PVAttr_NSImageView_Behavior_Animates;
extern PVAttrIdentifier const PVAttr_NSImageView_Behavior_Editable;
extern PVAttrIdentifier const PVAttr_NSImageView_ContentTintColor_ContentTintColor;


extern PVAttrIdentifier const PVAttr_NSControl_State_Enabled;
extern PVAttrIdentifier const PVAttr_NSControl_State_Highlighted;
extern PVAttrIdentifier const PVAttr_NSControl_State_Continuous;
extern PVAttrIdentifier const PVAttr_NSControl_ControlSize_Size;
extern PVAttrIdentifier const PVAttr_NSControl_Font_Name;
extern PVAttrIdentifier const PVAttr_NSControl_Font_Size;
extern PVAttrIdentifier const PVAttr_NSControl_Alignment_Alignment;
extern PVAttrIdentifier const PVAttr_NSControl_Misc_WritingDirection;
extern PVAttrIdentifier const PVAttr_NSControl_Misc_IgnoresMultiClick;
extern PVAttrIdentifier const PVAttr_NSControl_Misc_UsesSingleLineMode;
extern PVAttrIdentifier const PVAttr_NSControl_Misc_AllowsExpansionToolTips;
extern PVAttrIdentifier const PVAttr_NSControl_Value_StringValue;
extern PVAttrIdentifier const PVAttr_NSControl_Value_IntValue;
extern PVAttrIdentifier const PVAttr_NSControl_Value_IntegerValue;
extern PVAttrIdentifier const PVAttr_NSControl_Value_FloatValue;
extern PVAttrIdentifier const PVAttr_NSControl_Value_DoubleValue;
extern PVAttrIdentifier const PVAttr_NSButton_ButtonType_ButtonType;
extern PVAttrIdentifier const PVAttr_NSButton_Title_Title;
extern PVAttrIdentifier const PVAttr_NSButton_Title_AlernateTitle;
extern PVAttrIdentifier const PVAttr_NSButton_BezelStyle_BezelStyle;
extern PVAttrIdentifier const PVAttr_NSButton_Bordered_Bordered;
extern PVAttrIdentifier const PVAttr_NSButton_Transparent_Transparent;
extern PVAttrIdentifier const PVAttr_NSButton_BezelColor_BezelColor;
extern PVAttrIdentifier const PVAttr_NSButton_ContentTintColor_ContentTintColor;
extern PVAttrIdentifier const PVAttr_NSButton_Misc_ShowsBorderOnlyWhileMouseInside;
extern PVAttrIdentifier const PVAttr_NSButton_Misc_MaxAcceleratorLevel;
extern PVAttrIdentifier const PVAttr_NSButton_Misc_SpringLoaded;
extern PVAttrIdentifier const PVAttr_NSButton_Misc_HasDestructiveAction;
extern PVAttrIdentifier const PVAttr_NSScrollView_ContentOffset_Offset;
extern PVAttrIdentifier const PVAttr_NSScrollView_ContentSize_Size;
extern PVAttrIdentifier const PVAttr_NSScrollView_ContentInset_ContentInset;
extern PVAttrIdentifier const PVAttr_NSScrollView_ContentInset_AutomaticallyAdjustsContentInsets;
extern PVAttrIdentifier const PVAttr_NSScrollView_BorderType_BorderType;
extern PVAttrIdentifier const PVAttr_NSScrollView_Scroller_Horizontal;
extern PVAttrIdentifier const PVAttr_NSScrollView_Scroller_Vertical;
extern PVAttrIdentifier const PVAttr_NSScrollView_Scroller_AutohidesScrollers;
extern PVAttrIdentifier const PVAttr_NSScrollView_Scroller_ScrollerStyle;
extern PVAttrIdentifier const PVAttr_NSScrollView_Scroller_ScrollerKnobStyle;
extern PVAttrIdentifier const PVAttr_NSScrollView_Scroller_ScrollerInsets;
extern PVAttrIdentifier const PVAttr_NSScrollView_Ruler_Horizontal;
extern PVAttrIdentifier const PVAttr_NSScrollView_Ruler_Vertical;
extern PVAttrIdentifier const PVAttr_NSScrollView_Ruler_Visible;
extern PVAttrIdentifier const PVAttr_NSScrollView_LineScroll_Horizontal;
extern PVAttrIdentifier const PVAttr_NSScrollView_LineScroll_Vertical;
extern PVAttrIdentifier const PVAttr_NSScrollView_LineScroll_LineScroll;
extern PVAttrIdentifier const PVAttr_NSScrollView_PageScroll_Horizontal;
extern PVAttrIdentifier const PVAttr_NSScrollView_PageScroll_Vertical;
extern PVAttrIdentifier const PVAttr_NSScrollView_PageScroll_PageScroll;
extern PVAttrIdentifier const PVAttr_NSScrollView_ScrollElasiticity_Horizontal;
extern PVAttrIdentifier const PVAttr_NSScrollView_ScrollElasiticity_Vertical;
extern PVAttrIdentifier const PVAttr_NSScrollView_Misc_ScrollsDynamically;
extern PVAttrIdentifier const PVAttr_NSScrollView_Misc_UsesPredominantAxisScrolling;
extern PVAttrIdentifier const PVAttr_NSScrollView_Magnification_AllowsMagnification;
extern PVAttrIdentifier const PVAttr_NSScrollView_Magnification_Magnification;
extern PVAttrIdentifier const PVAttr_NSScrollView_Magnification_Max;
extern PVAttrIdentifier const PVAttr_NSScrollView_Magnification_Min;
extern PVAttrIdentifier const PVAttr_NSTableView_AllowsColumnReordering_AllowsColumnReordering;
extern PVAttrIdentifier const PVAttr_NSTableView_AllowsColumnResizing_AllowsColumnResizing;
extern PVAttrIdentifier const PVAttr_NSTableView_ColumnAutoresizingStyle_ColumnAutoresizingStyle;
extern PVAttrIdentifier const PVAttr_NSTableView_GridStyleMask_GridStyleMask;
extern PVAttrIdentifier const PVAttr_NSTableView_IntercellSpacing_IntercellSpacing;
extern PVAttrIdentifier const PVAttr_NSTableView_UseAlternatingRowBackgroundColors_UseAlternatingRowBackgroundColors;
extern PVAttrIdentifier const PVAttr_NSTableView_GridColor_GridColor;
extern PVAttrIdentifier const PVAttr_NSTableView_RowSizeStyle_RowSizeStyle;
extern PVAttrIdentifier const PVAttr_NSTableView_RowHeight_RowHeight;
extern PVAttrIdentifier const PVAttr_NSTableView_NumberOfRows_NumberOfRows;
extern PVAttrIdentifier const PVAttr_NSTableView_NumberOfColumns_NumberOfColumns;
extern PVAttrIdentifier const PVAttr_NSTableView_VerticalMotionCanBeginDrag_VerticalMotionCanBeginDrag;
extern PVAttrIdentifier const PVAttr_NSTableView_AllowsMultipleSelection_AllowsMultipleSelection;
extern PVAttrIdentifier const PVAttr_NSTableView_AllowsEmptySelection_AllowsEmptySelection;
extern PVAttrIdentifier const PVAttr_NSTableView_AllowsColumnSelection_AllowsColumnSelection;
extern PVAttrIdentifier const PVAttr_NSTableView_AllowsTypeSelect_AllowsTypeSelect;
extern PVAttrIdentifier const PVAttr_NSTableView_SelectionHighlightStyle_SelectionHighlightStyle;
extern PVAttrIdentifier const PVAttr_NSTableView_DraggingDestinationFeedbackStyle_DraggingDestinationFeedbackStyle;
extern PVAttrIdentifier const PVAttr_NSTableView_AutomaticRowHeights_AutomaticRowHeights;
extern PVAttrIdentifier const PVAttr_NSTableView_AutosaveName_AutosaveName;
extern PVAttrIdentifier const PVAttr_NSTableView_AutosaveTableColumns_AutosaveTableColumns;
extern PVAttrIdentifier const PVAttr_NSTableView_FloatsGroupRows_FloatsGroupRows;
extern PVAttrIdentifier const PVAttr_NSTableView_RowActionsVisible_RowActionsVisible;
extern PVAttrIdentifier const PVAttr_NSTableView_UsesStaticContents_UsesStaticContents;
extern PVAttrIdentifier const PVAttr_NSTableView_UserInterfaceLayoutDirection_UserInterfaceLayoutDirection;
extern PVAttrIdentifier const PVAttr_NSTableView_Style_Style;
extern PVAttrIdentifier const PVAttr_NSTextView_Font_Name;
extern PVAttrIdentifier const PVAttr_NSTextView_Font_Size;
extern PVAttrIdentifier const PVAttr_NSTextView_Basic_Editable;
extern PVAttrIdentifier const PVAttr_NSTextView_Basic_Selectable;
extern PVAttrIdentifier const PVAttr_NSTextView_Basic_RichText;
extern PVAttrIdentifier const PVAttr_NSTextView_Basic_FieldEditor;
extern PVAttrIdentifier const PVAttr_NSTextView_Basic_ImportsGraphics;
extern PVAttrIdentifier const PVAttr_NSTextView_String_String;
extern PVAttrIdentifier const PVAttr_NSTextView_TextColor_Color;
extern PVAttrIdentifier const PVAttr_NSTextView_Alignment_Alignment;
extern PVAttrIdentifier const PVAttr_NSTextView_ContainerInset_Inset;
extern PVAttrIdentifier const PVAttr_NSTextView_BaseWritingDirection_BaseWritingDirection;
extern PVAttrIdentifier const PVAttr_NSTextView_MaxSize_MaxSize;
extern PVAttrIdentifier const PVAttr_NSTextView_MinSize_MinSize;
extern PVAttrIdentifier const PVAttr_NSTextView_Resizable_Horizontal;
extern PVAttrIdentifier const PVAttr_NSTextView_Resizable_Vertical;
extern PVAttrIdentifier const PVAttr_NSTextField_Bordered_Bordered;
extern PVAttrIdentifier const PVAttr_NSTextField_Bezeled_Bezeled;
extern PVAttrIdentifier const PVAttr_NSTextField_Editable_Editable;
extern PVAttrIdentifier const PVAttr_NSTextField_Selectable_Selectable;
extern PVAttrIdentifier const PVAttr_NSTextField_DrawsBackground_DrawsBackground;
extern PVAttrIdentifier const PVAttr_NSTextField_BezelStyle_BezelStyle;
extern PVAttrIdentifier const PVAttr_NSTextField_PreferredMaxLayoutWidth_PreferredMaxLayoutWidth;
extern PVAttrIdentifier const PVAttr_NSTextField_MaximumNumberOfLines_MaximumNumberOfLines;
extern PVAttrIdentifier const PVAttr_NSTextField_AllowsDefaultTighteningForTruncation_AllowsDefaultTighteningForTruncation;
extern PVAttrIdentifier const PVAttr_NSTextField_LineBreakStrategy_LineBreakStrategy;
extern PVAttrIdentifier const PVAttr_NSTextField_Placeholder_Placeholder;
extern PVAttrIdentifier const PVAttr_NSTextField_TextColor_Color;
extern PVAttrIdentifier const PVAttr_NSTextField_BackgroundColor_Color;
extern PVAttrIdentifier const PVAttr_NSTextField_AllowsEditingTextAttributes_AllowsEditingTextAttributes;
extern PVAttrIdentifier const PVAttr_NSTextField_ImportsGraphics_ImportsGraphics;
extern PVAttrIdentifier const PVAttr_NSVisualEffectView_Material_Material;
extern PVAttrIdentifier const PVAttr_NSVisualEffectView_InteriorBackgroundStyle_InteriorBackgroundStyle;
extern PVAttrIdentifier const PVAttr_NSVisualEffectView_BlendingMode_BlendingMode;
extern PVAttrIdentifier const PVAttr_NSVisualEffectView_State_State;
extern PVAttrIdentifier const PVAttr_NSVisualEffectView_Emphasized_Emphasized;
extern PVAttrIdentifier const PVAttr_NSStackView_Orientation_Orientation;
extern PVAttrIdentifier const PVAttr_NSStackView_EdgeInsets_EdgeInsets;
extern PVAttrIdentifier const PVAttr_NSStackView_DetachesHiddenViews_DetachesHiddenViews;
extern PVAttrIdentifier const PVAttr_NSStackView_Distribution_Distribution;
extern PVAttrIdentifier const PVAttr_NSStackView_Alignment_Alignment;
extern PVAttrIdentifier const PVAttr_NSStackView_Spacing_Spacing;

extern PVAttrIdentifier const PVAttr_NSWindow_Title_Title;
extern PVAttrIdentifier const PVAttr_NSWindow_Title_Subtitle;
extern PVAttrIdentifier const PVAttr_NSWindow_State_KeyWindow;
extern PVAttrIdentifier const PVAttr_NSWindow_State_MainWindow;
extern PVAttrIdentifier const PVAttr_NSWindow_State_Visible;
extern PVAttrIdentifier const PVAttr_NSWindow_State_CanBecomeKeyWindow;
extern PVAttrIdentifier const PVAttr_NSWindow_State_CanBecomeMainWindow;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_Titled;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_Closable;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_Miniaturizable;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_Resizable;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_UnifiedTitleAndToolbar;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_FullScreen;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_FullSizeContentView;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_UtilityWindow;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_DocModalWindow;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_NonactivatingPanel;
extern PVAttrIdentifier const PVAttr_NSWindow_Style_HUDWindow;
extern PVAttrIdentifier const PVAttr_NSWindow_CollectionBehavior_CanJoinAllSpaces;
extern PVAttrIdentifier const PVAttr_NSWindow_CollectionBehavior_MoveToActiveSpace;
extern PVAttrIdentifier const PVAttr_NSWindow_CollectionBehavior_ParticipatesInCycle;
extern PVAttrIdentifier const PVAttr_NSWindow_CollectionBehavior_IgnoresCycle;
extern PVAttrIdentifier const PVAttr_NSWindow_CollectionBehavior_FullScreenPrimary;
extern PVAttrIdentifier const PVAttr_NSWindow_CollectionBehavior_FullScreenAuxiliary;
extern PVAttrIdentifier const PVAttr_NSWindow_CollectionBehavior_FullScreenNone;
extern PVAttrIdentifier const PVAttr_NSWindow_CollectionBehavior_FullScreenAllowsTiling;
extern PVAttrIdentifier const PVAttr_NSWindow_CollectionBehavior_FullScreenDisallowsTiling;
extern PVAttrIdentifier const PVAttr_NSWindow_Appearance_TitlebarAppearsTransparent;
extern PVAttrIdentifier const PVAttr_NSWindow_Appearance_TitleVisibility;
extern PVAttrIdentifier const PVAttr_NSWindow_Appearance_ToolbarStyle;
extern PVAttrIdentifier const PVAttr_NSWindow_Appearance_TitlebarSeparatorStyle;
extern PVAttrIdentifier const PVAttr_NSWindow_Appearance_BackgroundColor;
extern PVAttrIdentifier const PVAttr_NSWindow_Appearance_AlphaValue;
extern PVAttrIdentifier const PVAttr_NSWindow_Appearance_Opaque;
extern PVAttrIdentifier const PVAttr_NSWindow_Appearance_HasShadow;
extern PVAttrIdentifier const PVAttr_NSWindow_Behavior_Movable;
extern PVAttrIdentifier const PVAttr_NSWindow_Behavior_MovableByWindowBackground;
extern PVAttrIdentifier const PVAttr_NSWindow_Behavior_AnimationBehavior;
extern PVAttrIdentifier const PVAttr_NSWindow_Behavior_Level;
extern PVAttrIdentifier const PVAttr_NSWindow_Behavior_HidesOnDeactivate;
extern PVAttrIdentifier const PVAttr_NSWindow_Behavior_TabbingMode;
extern PVAttrIdentifier const PVAttr_NSWindow_Size_MinSize;
extern PVAttrIdentifier const PVAttr_NSWindow_Size_MaxSize;
extern PVAttrIdentifier const PVAttr_NSWindow_Info_WindowNumber;
extern PVAttrIdentifier const PVAttr_NSWindow_Info_BackingScaleFactor;

// UIWindowScene
extern PVAttrGroupIdentifier const PVAttrGroup_UIWindowScene;

extern PVAttrSectionIdentifier const PVAttrSec_UIWindowScene_State;
extern PVAttrSectionIdentifier const PVAttrSec_UIWindowScene_Title;
extern PVAttrSectionIdentifier const PVAttrSec_UIWindowScene_Orientation;
extern PVAttrSectionIdentifier const PVAttrSec_UIWindowScene_Windows;
extern PVAttrSectionIdentifier const PVAttrSec_UIWindowScene_Screen;
extern PVAttrSectionIdentifier const PVAttrSec_UIWindowScene_StatusBar;
extern PVAttrSectionIdentifier const PVAttrSec_UIWindowScene_Traits;
extern PVAttrSectionIdentifier const PVAttrSec_UIWindowScene_Session;

// UITraitCollection
extern PVAttrSectionIdentifier const PVAttrSec_UITraitCollection_Appearance;
extern PVAttrSectionIdentifier const PVAttrSec_UITraitCollection_SizeClass;
extern PVAttrSectionIdentifier const PVAttrSec_UITraitCollection_Display;
extern PVAttrSectionIdentifier const PVAttrSec_UITraitCollection_Device;
extern PVAttrSectionIdentifier const PVAttrSec_UITraitCollection_Layout;
extern PVAttrSectionIdentifier const PVAttrSec_UITraitCollection_Content;

extern PVAttrIdentifier const PVAttr_UIWindowScene_State_ActivationState;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Title_Title;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Orientation_InterfaceOrientation;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Windows_WindowCount;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Windows_KeyWindowClassName;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Screen_ScreenBounds;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Screen_ScreenScale;
extern PVAttrIdentifier const PVAttr_UIWindowScene_StatusBar_StatusBarHidden;
extern PVAttrIdentifier const PVAttr_UIWindowScene_StatusBar_StatusBarStyle;
extern PVAttrIdentifier const PVAttr_UIWindowScene_StatusBar_StatusBarFrame;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_UserInterfaceStyle;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_HorizontalSizeClass;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_VerticalSizeClass;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_UserInterfaceLevel;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_ActiveAppearance;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_AccessibilityContrast;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_LegibilityWeight;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_DisplayScale;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_DisplayGamut;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_UserInterfaceIdiom;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_LayoutDirection;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_PreferredContentSizeCategory;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_SceneCaptureState;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_ImageDynamicRange;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Traits_TypesettingLanguage;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Session_PersistentIdentifier;
extern PVAttrIdentifier const PVAttr_UIWindowScene_Session_SessionRole;

// UITraitCollection
extern PVAttrIdentifier const PVAttr_UITraitCollection_Appearance_UserInterfaceStyle;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Appearance_UserInterfaceLevel;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Appearance_ActiveAppearance;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Appearance_AccessibilityContrast;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Appearance_LegibilityWeight;
extern PVAttrIdentifier const PVAttr_UITraitCollection_SizeClass_HorizontalSizeClass;
extern PVAttrIdentifier const PVAttr_UITraitCollection_SizeClass_VerticalSizeClass;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Display_DisplayScale;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Display_DisplayGamut;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Display_ImageDynamicRange;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Device_UserInterfaceIdiom;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Device_ForceTouchCapability;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Layout_LayoutDirection;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Content_PreferredContentSizeCategory;
extern PVAttrIdentifier const PVAttr_UITraitCollection_Content_TypesettingLanguage;
